{
  "hash": "5747d4a0143b3bcab453c4958a165915",
  "result": {
    "engine": "jupyter",
    "markdown": "# Handling missing values\n\nWe cover how to detect missing values, how to remove rows or columns with missing values, and how to replace missing values in DataFrames.\n\n{{< video https://vimeo.com/1195887666/4465f653de?fl=ml&fe=ec >}}\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# ── Detecting missing values ─────────────────────────────────\n\n# Count missing values per column\ntitanic.isna().sum()\n\n# Share of missing values per column\ntitanic.isna().mean().round(3)\n\n# Rows with missing age\ntitanic[titanic[\"age\"].isna()]\n\n# Rows with value for age\ntitanic[titanic[\"age\"].notna()]\n\n# ── Dropping missing values ──────────────────────────────────\n\nprint(\"Before:\", len(titanic))\ntitanic_clean = titanic.dropna()\nprint(\"After dropping all NaN:\", len(titanic_clean))\n\n# Only drop rows where age is missing\ntitanic_no_missing_age = titanic.dropna(subset=[\"age\"])\nprint(\"After dropping missing age:\", len(titanic_no_missing_age))\n\n# ── Filling missing values ───────────────────────────────────\n\n# Fill missing age with the median age\nmedian_age = titanic[\"age\"].median()\nprint(\"Median age:\", median_age)\n\ntitanic[\"age\"] = titanic[\"age\"].fillna(median_age)\nprint(\"Missing age after fill:\", titanic[\"age\"].isna().sum())\n\n# ── Missing values and data types ────────────────────────────\n\nprint(titanic[\"age\"].dtype)\n\ntitanic[\"age\"] = titanic[\"age\"].astype(int)\nprint(titanic[\"age\"].dtype)\ntitanic.head()\n\n```\n\n## Exercises\n\n### Exercise 3.6.1\n\nThe `healthexp` dataset is an **unbalanced panel** — not every country is observed in every year. To see this clearly, we can convert it into a **balanced panel** by creating a DataFrame with a row for every possible country-year combination, filling in the observed values where they exist and leaving the rest as `NaN`.\n\nRun the code below to create the balanced panel, then answer the questions.\n\n```python\nimport pandas as pd\n\nhealthexp = pd.read_csv(\"data/healthexp.csv\")\n\n# Create all combinations of country and year\nidx = pd.MultiIndex.from_product(\n    [healthexp[\"Country\"].unique(), healthexp[\"Year\"].unique()],\n    names=[\"Country\", \"Year\"]\n)\nhealthexp_balanced = (\n    healthexp\n    .set_index([\"Country\", \"Year\"])\n    .reindex(idx)\n    .reset_index()\n)\n```\n\n1. How many rows does `healthexp` have before and after the reindex? What does the difference tell you about the panel?\n2. Use `.isna().sum()` to count missing values per column in `healthexp_balanced`. Which columns have missing values and how many?\n3. Use `.isna().mean().round(3)` to compute the share of missing values per column. Which country-year combinations are missing? Filter to rows where `Spending_USD` is missing and print the result to identify them.\n\n<details>\n<summary>Solution</summary>\n\n::: {#f6019e58 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\n\nhealthexp = pd.read_csv(\"data/healthexp.csv\")\n\nprint(\"Before:\", len(healthexp))\n\nidx = pd.MultiIndex.from_product(\n    [healthexp[\"Country\"].unique(), healthexp[\"Year\"].unique()],\n    names=[\"Country\", \"Year\"]\n)\nhealthexp_balanced = (\n    healthexp\n    .set_index([\"Country\", \"Year\"])\n    .reindex(idx)\n    .reset_index()\n)\n\nprint(\"After:\", len(healthexp_balanced))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBefore: 274\nAfter: 306\n```\n:::\n:::\n\n\n::: {#ad4e4c10 .cell execution_count=2}\n``` {.python .cell-code}\nprint(healthexp_balanced.isna().sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCountry             0\nYear                0\nSpending_USD       32\nLife_Expectancy    32\ndtype: int64\n```\n:::\n:::\n\n\n::: {#8111a630 .cell execution_count=3}\n``` {.python .cell-code}\nprint(healthexp_balanced.isna().mean().round(3))\nprint(healthexp_balanced[healthexp_balanced[\"Spending_USD\"].isna()])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCountry            0.000\nYear               0.000\nSpending_USD       0.105\nLife_Expectancy    0.105\ndtype: float64\n           Country  Year  Spending_USD  Life_Expectancy\n21         Germany  1991           NaN              NaN\n52          France  1971           NaN              NaN\n53          France  1972           NaN              NaN\n54          France  1973           NaN              NaN\n55          France  1974           NaN              NaN\n57          France  1976           NaN              NaN\n58          France  1977           NaN              NaN\n59          France  1978           NaN              NaN\n60          France  1979           NaN              NaN\n62          France  1981           NaN              NaN\n63          France  1982           NaN              NaN\n64          France  1983           NaN              NaN\n65          France  1984           NaN              NaN\n67          France  1986           NaN              NaN\n68          France  1987           NaN              NaN\n69          France  1988           NaN              NaN\n70          France  1989           NaN              NaN\n104  Great Britain  1972           NaN              NaN\n105  Great Britain  1973           NaN              NaN\n106  Great Britain  1974           NaN              NaN\n107  Great Britain  1975           NaN              NaN\n108  Great Britain  1976           NaN              NaN\n109  Great Britain  1977           NaN              NaN\n110  Great Britain  1978           NaN              NaN\n111  Great Britain  1979           NaN              NaN\n255         Canada  1970           NaN              NaN\n257         Canada  1972           NaN              NaN\n258         Canada  1973           NaN              NaN\n259         Canada  1974           NaN              NaN\n260         Canada  1975           NaN              NaN\n262         Canada  1977           NaN              NaN\n263         Canada  1978           NaN              NaN\n```\n:::\n:::\n\n\n1. `healthexp` has 274 rows before reindexing, whereas the balanced panel has 306. The difference represents country-year combinations that were not observed in the original data, confirming the panel is unbalanced.\n\n2. Both `Spending_USD` and `Life_Expectancy` have 32 missing values — one per unobserved country-year combination. `Country` and `Year` have no missing values because every combination was explicitly created by `from_product()`.\n\n3. The missing rows is mainly caused by the fact that that not all countries are observed each year at the beginning of the sample, e.g., France is observed only every fifth year until 1990. This is a structural pattern in the missingness, not random\ndata loss, which is important to understand before deciding how to handle it.\n\n</details>\n\n---\n\n### Exercise 3.6.2\n\nThe `deck` column in the Titanic dataset has a very high share of missing values. This exercise explores what happens when you use `.dropna()` without thinking carefully about which columns matter.\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n```\n\n1. Use `.isna().sum()` and `.isna().mean().round(3)` to profile the missing values across all columns. Which column has by far the most missing values, and what share of rows are missing?\n2. Run `titanic.dropna()` without any arguments and print how many rows remain. Explain why so many rows are lost.\n3. Use the `subset=` parameter to drop only rows where `embarked` is missing. How many rows are removed this time? Why is this a more sensible choice than dropping all rows with any missing value?\n4. Instead of dropping rows, you can also drop entire columns using the `axis=` parameter in `.dropna()`. Look up the documentation for `pd.DataFrame.dropna()` and use `axis=1` to drop all columns that contain any missing values. Which columns are removed? Is this a sensible approach for the `deck` column?\n\n<details>\n<summary>Solution</summary>\n\n::: {#99b3834d .cell execution_count=4}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# 1. Profile missing values\nprint(titanic.isna().sum())\nprint(titanic.isna().mean().round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsurvived         0\npclass           0\nsex              0\nage            177\nsibsp            0\nparch            0\nfare             0\nembarked         2\nclass            0\nwho              0\nadult_male       0\ndeck           688\nembark_town      2\nalive            0\nalone            0\ndtype: int64\nsurvived       0.000\npclass         0.000\nsex            0.000\nage            0.199\nsibsp          0.000\nparch          0.000\nfare           0.000\nembarked       0.002\nclass          0.000\nwho            0.000\nadult_male     0.000\ndeck           0.772\nembark_town    0.002\nalive          0.000\nalone          0.000\ndtype: float64\n```\n:::\n:::\n\n\n::: {#136e1c7b .cell execution_count=5}\n``` {.python .cell-code}\n# 2. dropna() without arguments\ntitanic_clean = titanic.dropna()\nprint(\"Rows remaining:\", len(titanic_clean))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows remaining: 182\n```\n:::\n:::\n\n\n::: {#6d35ea6a .cell execution_count=6}\n``` {.python .cell-code}\n# 3. dropna() with subset=\ntitanic_clean_embarked = titanic.dropna(subset=[\"embarked\"])\nprint(\"Rows remaining:\", len(titanic_clean_embarked))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows remaining: 889\n```\n:::\n:::\n\n\n::: {#40970738 .cell execution_count=7}\n``` {.python .cell-code}\n# 4. dropna() with axis=1\ntitanic_cols_dropped = titanic.dropna(axis=1)\nprint(titanic_cols_dropped.columns.tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n['survived', 'pclass', 'sex', 'sibsp', 'parch', 'fare', 'class', 'who', 'adult_male', 'alive', 'alone']\n```\n:::\n:::\n\n\n1. The `deck` column is missing for approximately 77% of passengers — by far the most incomplete column in the dataset. `age` is missing for about 20% of passengers. All other columns are nearly complete.\n\n2. Only 182 rows remain after `dropna()` — down from 891. This is because `dropna()` removes any row that has a missing value in *any* column. Since `deck` is missing for 688 passengers, almost the entire dataset is dropped. Using `dropna()` without arguments on a dataset with unevenly distributed missingness is almost never the right choice.\n\n3. Only 2 rows are removed when using `subset=[\"embarked\"]`. This is a much more surgical approach: we remove only the rows where the specific column we care about is incomplete, leaving the rest of the data intact.\n\n4. `axis=1` drops any column that contains at least one missing value, removing `age`, `deck`, `embarked` and `embark_town`. For `deck` — where 77% of values are missing — this is a reasonable decision. For `age` and `embarked`, it is far too aggressive: `age` is an important variable and only 20% missing, while `embarked` and `embark_town` have just 2 missing values out of 891. As with row-dropping, column-dropping with `axis=1` should be used deliberately and targeted at specific columns rather than applied blindly across the entire DataFrame.\n\n</details>\n\n---\n\n### Exercise 3.6.3\n\nThe `fare` column in the Titanic dataset has no missing values, so no imputation is needed. However, it is still worth thinking about what you *would* do if it did have missing values — because the right imputation strategy depends on the distribution of the data, not just the function you use.\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n```\n\n1. Compute both the mean and median of the `fare` column and print them side by side. How large is the difference between them?\n2. Plot a quick histogram of `fare` by running `titanic[\"fare\"].plot.hist(bins=30)`. What does the shape of the distribution tell you?\n3. If `fare` did have missing values, which would be the more appropriate imputation value — the mean or the median? Explain your reasoning.\n\n<details>\n<summary>Solution</summary>\n\n::: {#b1723872 .cell execution_count=8}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# 1. Mean vs median\nprint(\"Mean fare:  \", titanic[\"fare\"].mean().round(2))\nprint(\"Median fare:\", titanic[\"fare\"].median().round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean fare:   32.2\nMedian fare: 14.45\n```\n:::\n:::\n\n\n::: {#01173b8a .cell execution_count=9}\n``` {.python .cell-code}\n# 2. Histogram\ntitanic[\"fare\"].plot.hist(bins=30)\n```\n\n::: {.cell-output .cell-output-display}\n![](03-06-missing-values_files/figure-html/cell-10-output-1.png){width=593 height=411}\n:::\n:::\n\n\n1. The mean fare is considerably higher than the median — a clear sign that the two statistics are telling different stories about the same data.\n\n2. The histogram shows a strongly right-skewed distribution: the vast majority of passengers paid a relatively low fare, but a small number paid very high fares — some above 500. These high-fare outliers pull the mean upward while the median remains closer to what a typical passenger actually paid.\n\n3. The median would be the more appropriate imputation value. Because the distribution is skewed, the mean does not represent a typical fare — imputing missing values with the mean would assign an unusually high fare to passengers who most likely paid something closer to the median. As a general rule, use the median for skewed distributions and the mean only when the distribution is\napproximately symmetric.\n\n</details>\n\n---\n\n### Exercise 3.6.4\n\nIn this exercise you will artificially introduce missing values into the `flights` dataset and then use forward-filling to impute them.\n\nRun the code below to remove passenger counts for all months in 1954 and 1957:\n\n```python\nimport pandas as pd\n\nflights = pd.read_csv(\"data/flights.csv\")\n\nflights_missing = flights.copy()\nflights_missing.loc[\n    flights_missing[\"year\"].isin([1954, 1957]), \"passengers\"\n] = None\n\nprint(flights_missing[\"passengers\"].isna().sum())\n```\n\n1. Look up the documentation for `.ffill()` by running `help(pd.DataFrame.ffill)` in the console. What does it do?\n2. The `flights` dataset is sorted by year first, then month. Apply `.ffill()` to fill the missing passenger values and print the imputed values for 1954. Do the imputed values look reasonable? Which observation is being used to fill January 1954, and why is this a poor estimate?\n3. Sort `flights_missing` by `month` first and then `year`, and apply `.ffill()` again. Print the imputed values for 1954 and compare them against the actual values in the original `flights` dataset. Why does this sort order produce better imputations?\n\n<details>\n<summary>Hint</summary>\n\nWhen the data is sorted by month first, the row immediately above January 1954 is January 1953. This means `.ffill()` uses the same month from the previous year as the estimate — a much more sensible choice for seasonal data than using the previous month from a different season.\n\n</details>\n\n<details>\n<summary>Solution</summary>\n\n::: {#008dec31 .cell execution_count=10}\n``` {.python .cell-code}\nimport pandas as pd\n\nflights = pd.read_csv(\"data/flights.csv\")\n\nflights_missing = flights.copy()\nflights_missing.loc[\n    flights_missing[\"year\"].isin([1954, 1957]), \"passengers\"\n] = None\n\n# 2. ffill() with default sort order (year first)\nflights_year_sort = flights_missing.copy()\nflights_year_sort[\"passengers\"] = flights_year_sort[\"passengers\"].ffill()\nprint(flights_year_sort[flights_year_sort[\"year\"] == 1954][[\"year\", \"month\", \"passengers\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    year month  passengers\n60  1954   Jan       201.0\n61  1954   Feb       201.0\n62  1954   Mar       201.0\n63  1954   Apr       201.0\n64  1954   May       201.0\n65  1954   Jun       201.0\n66  1954   Jul       201.0\n67  1954   Aug       201.0\n68  1954   Sep       201.0\n69  1954   Oct       201.0\n70  1954   Nov       201.0\n71  1954   Dec       201.0\n```\n:::\n:::\n\n\n::: {#2bb5dd82 .cell execution_count=11}\n``` {.python .cell-code}\n# 3. Sort by month first, then year, and apply ffill()\nflights_month_sort = flights_missing.sort_values([\"month\", \"year\"]).reset_index(drop=True)\nflights_month_sort[\"passengers\"] = flights_month_sort[\"passengers\"].ffill()\n\n# Compare imputed vs actual for 1954\nimputed = flights_month_sort[flights_month_sort[\"year\"] == 1954].sort_values(\"month\")\nactual  = flights[flights[\"year\"] == 1954].sort_values(\"month\")\n\ncomparison = pd.DataFrame({\n    \"month\":   actual[\"month\"].values,\n    \"imputed\": imputed[\"passengers\"].values,\n    \"actual\":  actual[\"passengers\"].values,\n    \"diff\":    actual[\"passengers\"].values - imputed[\"passengers\"].values\n})\nprint(comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   month  imputed  actual  diff\n0    Apr    235.0     227  -8.0\n1    Aug    272.0     293  21.0\n2    Dec    201.0     229  28.0\n3    Feb    196.0     188  -8.0\n4    Jan    196.0     204   8.0\n5    Jul    264.0     302  38.0\n6    Jun    243.0     264  21.0\n7    Mar    236.0     235  -1.0\n8    May    229.0     234   5.0\n9    Nov    180.0     203  23.0\n10   Oct    211.0     229  18.0\n11   Sep    237.0     259  22.0\n```\n:::\n:::\n\n\n2. With the default year-first sort, `.ffill()` fills January 1954 with the value from December 1953 — the last observed month before the gap. This is a poor estimate because December is a peak travel month while January is typically much quieter. The same problem affects all months in 1954.\n\n3. Sorting by month first means the row above January 1954 is January 1953, so `.ffill()` uses the same month from the prior year. For seasonal data like air travel this is a far better proxy. The imputed values are not perfect — they miss the upward trend in passenger numbers over time — but they correctly reflect the seasonal pattern within each year.\n\n</details>\n\n---\n\n### Exercise 3.6.5\n\nThis exercise asks you to think carefully about *how* to handle missing values rather than just *which function* to use. There is no single correct answer — the goal is to reason through each case.\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\nprint(titanic.isna().sum())\nprint(titanic.isna().mean().round(3))\n```\n\nFor each of the three columns below, decide whether you would **drop rows**, **fill with an imputed value**, **drop the column entirely**, or **leave as-is**. Write a short justification for each decision and, where you choose to fill, explain what value you would use.\n\n1. `age` — approximately 20% missing.\n2. `deck` — approximately 77% missing.\n3. `embarked` — 2 values missing out of 891.\n\nThere is no single right answer. Focus on reasoning through the tradeoffs clearly.\n\n<details>\n<summary>Solution</summary>\n\n::: {#6370fa60 .cell execution_count=12}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\nprint(titanic.isna().sum())\nprint(titanic.isna().mean().round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsurvived         0\npclass           0\nsex              0\nage            177\nsibsp            0\nparch            0\nfare             0\nembarked         2\nclass            0\nwho              0\nadult_male       0\ndeck           688\nembark_town      2\nalive            0\nalone            0\ndtype: int64\nsurvived       0.000\npclass         0.000\nsex            0.000\nage            0.199\nsibsp          0.000\nparch          0.000\nfare           0.000\nembarked       0.002\nclass          0.000\nwho            0.000\nadult_male     0.000\ndeck           0.772\nembark_town    0.002\nalive          0.000\nalone          0.000\ndtype: float64\n```\n:::\n:::\n\n\nThese are defensible choices — yours may differ, and that is fine as long as the reasoning is sound.\n\n1. **`age` — fill with median.** 20% is a substantial share to drop outright, and age is likely to be relevant in any survival analysis. Filling with the median is preferable to the mean because the age distribution may be skewed. Alternatively, you could fill using the median within each passenger class, which would give a more accurate estimate — but that requires `groupby`, which we cover in the next video.\n\n2. **`deck` — drop the column entirely.** 77% of values are missing, almost certainly because deck information was simply not recorded for most passengers. Filling 688 out of 891 rows with an imputed value would mean the column reflects our imputation method far more than it reflects reality. If deck is not critical to your analysis, dropping it is the cleanest choice. If it is important, you should document clearly that most values are imputed and treat results involving `deck` with caution.\n\n3. **`embarked` — drop the 2 rows.** Only 2 values are missing out of 891. The information loss from dropping these rows is negligible, and there is no sensible basis for imputing a categorical variable like port of embarkation. This is the clearest case: drop the rows.\n\n</details>\n\n",
    "supporting": [
      "03-06-missing-values_files"
    ],
    "filters": [],
    "includes": {}
  }
}