project:
  type: book
  output-dir: docs

book:
  title: "SKL401 — Introduction to Python"
  author: "Isabel Hovdahl, Department of Business and Management Science, NHH"
  chapters:
    - index.qmd
    - part: "1 - Getting Started and Working Effectively"
      chapters:
        - file: 01-getting-started-and-working-effectively/01-02-installing-python.qmd
          text: "1.2 Installing Python"
        - file: 01-getting-started-and-working-effectively/01-03-installing-positron.qmd
          text: "1.3 Installing and Touring Positron"
        - file: 01-getting-started-and-working-effectively/01-04-files-folders-paths.qmd
          text: "1.4 Files, Folders and Paths"
        - file: 01-getting-started-and-working-effectively/01-05-running-scripts.qmd
          text: "1.5 Writing and Running Your First Script"
        - file: 01-getting-started-and-working-effectively/01-06-packages.qmd
          text: "1.6 Installing and Importing Packages"
        - file: 01-getting-started-and-working-effectively/01-07-variables-data-types.qmd
          text: "1.7 Variables and Basic Data Types"
        - file: 01-getting-started-and-working-effectively/01-08-lists-dicts-arrays.qmd
          text: "1.8 Lists, Dictionaries and Arrays"
        - file: 01-getting-started-and-working-effectively/01-09-indexing-subsetting.qmd
          text: "1.9 Indexing and Subsetting"
        - file: 01-getting-started-and-working-effectively/01-10-dataframes.qmd
          text: "1.10 DataFrames: Your Most Important Object"
    - part: "2 - Programming Fundamentals"
      chapters:
        - file: 02-programming-fundamentals/02-01-placeholder.qmd
          text: "2.1 Placeholder"
    - part: "3 - Data Wrangling"
      chapters:
        - file: 03-data-wrangling/03-01-placeholder.qmd
          text: "3.1 Placeholder"
    - part: "4 - Graphics"
      chapters:
        - file: 04-graphics/04-01-placeholder.qmd
          text: "4.1 Placeholder"
    - part: "5 - Analysis, Reporting, and Wrap-up"
      chapters:
        - file: 05-analysis-reporting-and-wrap-up/05-01-placeholder.qmd
          text: "5.1 Placeholder"

format:
  html:
    number-sections: false
    theme: cosmo
