{
  "hash": "897fb4ed89136e69aae50bcf28807b48",
  "result": {
    "engine": "jupyter",
    "markdown": "# Importing data\n\nWe introduce the most common ways to get data into Python — loading built-in datasets via seaborn, and importing CSV and Excel files — and cover how to save DataFrames back to files.\n\n{{< video https://vimeo.com/1195888052/adbbfb2ebb?fl=ml&fe=ec >}}\n\n```python\nimport pandas as pd\nimport seaborn as sns\n\n# ── Loading a built-in dataset with seaborn ──────────────────\n\ntitanic = sns.load_dataset(\"titanic\")\ntitanic.shape\ntitanic.head()\n\n# Important checks\n# titanic.info()\n# titanic.describe()\n\n# ── Saving data to a file ────────────────────────────────────\n\n# Save to CSV\ntitanic.to_csv(\"data/titanic.csv\", index=False)\nprint(\"Saved to data/titanic.csv\")\n\n# Save to Excel\ntitanic.to_excel(\"data/titanic.xlsx\", index=False, sheet_name=\"titanic\")\nprint(\"Saved to data/titanic.xlsx\")\n\n# ── Loading from a file ──────────────────────────────────────\n\ntitanic_from_csv = pd.read_csv(\"data/titanic.csv\")\ntitanic_from_csv.head()\n\ntitanic_from_excel = pd.read_excel(\"data/titanic.xlsx\", sheet_name=\"titanic\")\ntitanic_from_excel.head()\n\n# ── The sep parameter for European CSV files ─────────────────\n\n# Save a semicolon-separated version to demonstrate\ntitanic.to_csv(\"data/titanic_semicolon.csv\", index=False, sep=\";\")\n\n# Load it back — must specify sep=\";\"\ntitanic_semi = pd.read_csv(\"data/titanic_semicolon.csv\", sep =\";\")\ntitanic_semi.head()\n\n# ── Saving and loading the other datasets ────────────────────\n\nhealthexp = sns.load_dataset(\"healthexp\")\nflights   = sns.load_dataset(\"flights\")\n\nhealthexp.to_csv(\"data/healthexp.csv\", index=False)\nflights.to_csv(\"data/flights.csv\", index=False)\n\nprint(\"healthexp saved:\", healthexp.shape)\nprint(\"flights saved:\",   flights.shape)\n\n```\n\n## Exercises\n\n### Exercise 3.1.1\n\nThe code from this video saves the Titanic dataset to your `data/` folder. Before moving on, make sure you have run that code and that the file exists on your computer.\n\nOpen the file browser in Positron (the folder icon in the left sidebar) and navigate to your `data/` folder. Confirm that `titanic.csv` is there.\n\nThen load the file and use `.info()` and `.describe()` to answer the following questions:\n\n1. How many passengers are in the dataset?\n2. Which columns have missing values, and how many values are missing in each?\n3. What is the mean fare paid by passengers?\n\n<details>\n<summary>Solution</summary>\n\n::: {#e956c847 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\ntitanic.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.DataFrame'>\nRangeIndex: 891 entries, 0 to 890\nData columns (total 15 columns):\n #   Column       Non-Null Count  Dtype  \n---  ------       --------------  -----  \n 0   survived     891 non-null    int64  \n 1   pclass       891 non-null    int64  \n 2   sex          891 non-null    str    \n 3   age          714 non-null    float64\n 4   sibsp        891 non-null    int64  \n 5   parch        891 non-null    int64  \n 6   fare         891 non-null    float64\n 7   embarked     889 non-null    str    \n 8   class        891 non-null    str    \n 9   who          891 non-null    str    \n 10  adult_male   891 non-null    bool   \n 11  deck         203 non-null    str    \n 12  embark_town  889 non-null    str    \n 13  alive        891 non-null    str    \n 14  alone        891 non-null    bool   \ndtypes: bool(2), float64(2), int64(4), str(7)\nmemory usage: 92.4 KB\n```\n:::\n:::\n\n\n::: {#e301bfc2 .cell execution_count=2}\n``` {.python .cell-code}\ntitanic.describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>survived</th>\n      <th>pclass</th>\n      <th>age</th>\n      <th>sibsp</th>\n      <th>parch</th>\n      <th>fare</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>891.000000</td>\n      <td>891.000000</td>\n      <td>714.000000</td>\n      <td>891.000000</td>\n      <td>891.000000</td>\n      <td>891.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>0.383838</td>\n      <td>2.308642</td>\n      <td>29.699118</td>\n      <td>0.523008</td>\n      <td>0.381594</td>\n      <td>32.204208</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>0.486592</td>\n      <td>0.836071</td>\n      <td>14.526497</td>\n      <td>1.102743</td>\n      <td>0.806057</td>\n      <td>49.693429</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>0.000000</td>\n      <td>1.000000</td>\n      <td>0.420000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>0.000000</td>\n      <td>2.000000</td>\n      <td>20.125000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>7.910400</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>0.000000</td>\n      <td>3.000000</td>\n      <td>28.000000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>14.454200</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>1.000000</td>\n      <td>3.000000</td>\n      <td>38.000000</td>\n      <td>1.000000</td>\n      <td>0.000000</td>\n      <td>31.000000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>1.000000</td>\n      <td>3.000000</td>\n      <td>80.000000</td>\n      <td>8.000000</td>\n      <td>6.000000</td>\n      <td>512.329200</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n1. There are 891 passengers (rows) in the dataset.\n2. Four columns have missing values: `age` (177 missing), `embarked` (2 missing), `deck` (688 missing) and `embark_town` (2 missing). You can read this from the `Non-Null Count` column in the `.info()` output — a column with 891 non-null values has no missing values, while fewer means some are missing.\n3. The mean fare is approximately 32.20, visible in the `mean` row of the `.describe()` output.\n\n</details>\n\n---\n\n### Exercise 3.1.2\n\nThe video code at the bottom of the script saves the `healthexp` and `flights` datasets to your `data/` folder. Run that code now if you have not already done so, then complete the steps below.\n\n**Step 1.** Open the file browser in Positron and navigate to your `data/` folder. Confirm that `healthexp.csv` and `flights.csv` are both there.\n\n**Step 2.** Find the full absolute path to your `data/` folder. You can do this by right-clicking the `data/` folder in the Positron file browser and selecting \"Copy Path\", or by running the following code in the console:\n\n```python\nimport os\nprint(os.path.abspath(\"data\"))\n```\n\nWrite down or copy this path — you will need it in the next exercise.\n\n**Step 3.** Load both files using `pd.read_csv()` and print the shape of each.\n\n<details>\n<summary>Solution</summary>\n\n::: {#65081484 .cell execution_count=3}\n``` {.python .cell-code}\nimport pandas as pd\n\nhealthexp = pd.read_csv(\"data/healthexp.csv\")\nflights   = pd.read_csv(\"data/flights.csv\")\n\nprint(healthexp.shape)\nprint(flights.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(274, 4)\n(144, 3)\n```\n:::\n:::\n\n\n`healthexp` has 274 rows and 4 columns. `flights` has 144 rows and 3 columns.\n\nThe absolute path printed by `os.path.abspath(\"data\")` will look different on\nevery computer, for example:\n\n- Windows: `C:\\Users\\yourname\\Documents\\skl401\\data`\n- Mac: `/Users/yourname/Documents/skl401/data`\n\nThis is the full address of the folder from the root of your file system. The relative path `\"data/titanic.csv\"` is a shortcut that only works because Python is currently running from your project folder — the folder that contains the `data/` subfolder.\n\n</details>\n\n---\n\n### Exercise 3.1.3\n\nThis exercise explores the difference between relative and absolute paths, and what can go wrong when you use the wrong one.\n\nRun the following code and look at the path that is printed:\n\n```python\nimport os\nprint(os.getcwd())\n```\n\n`os.getcwd()` returns the **working directory** — the folder Python is currently treating as its starting point. When you use a relative path like `\"data/titanic.csv\"`, Python looks for a `data/` folder inside this location.\n\nNow answer the following questions:\n\n1. Does the path printed match the project folder you set up at the start of the course — the folder that contains your scripts and your `data/` subfolder?\n\n2. Load `titanic.csv` using the full absolute path you found in Exercise 3.1.2 instead of the relative path. Confirm the result is identical. Note: if you are on Windows, your path will use backslashes (e.g. `C:\\Users\\yourname\\...`). Python requires forward slashes in paths, so replace any backslashes with forward slashes before running the code.\n\n3. Suppose a classmate copies only the script file to their Desktop and runs it from there, without copying the `data/` folder. Which path would work for them — the relative path or the absolute path you used in step 2? Explain why.\n\n<details>\n<summary>Solution</summary>\n\n```python\nimport os\nprint(os.getcwd())\n```\n\n```python\n# Replace this path with the absolute path on your own computer\ntitanic_abs = pd.read_csv(\"/Users/yourname/Documents/skl401/data/titanic.csv\")\ntitanic_abs.shape\n```\n\n1. Yes — if you opened Positron from your project folder and are running scripts from there, `os.getcwd()` should return that folder. If it shows something unexpected, check that Positron has the right folder open (Open → Open Folder...).\n\n2. The result is identical — `read_csv()` does not care whether you provide a relative or absolute path, as long as the path points to the same file.\n\n3. Neither path would work as-is. The relative path `\"data/titanic.csv\"` would fail because there is no `data/` folder on the Desktop. The absolute path would also fail because it points to a location on *your* computer, not theirs. To share a script that others can run, you either need to share the whole project folder (scripts and data together), or load data from a URL. Hard-coding absolute paths into scripts is a common mistake — they silently break the moment anyone else tries to run the code.\n\n</details>\n\n---\n\n### Exercise 3.1.4\n\nThe code below saves a small DataFrame to CSV and loads it back in. Run it and\ninspect the result.\n\n```python\nimport pandas as pd\n\nproducts = pd.DataFrame({\n    \"product\":  [\"coffee\", \"tea\", \"juice\"],\n    \"price\":    [29.90, 35.00, 12.50],\n    \"quantity\": [3, 5, 0]\n})\n\nproducts.to_csv(\"data/products.csv\")\n\nproducts_loaded = pd.read_csv(\"data/products.csv\")\nprint(products_loaded)\n```\n\n1. How many columns does `products_loaded` have compared to `products`? What is the extra column called, and where did it come from?\n2. Fix the `to_csv()` call so that the extra column does not appear when you reload the file.\n\n<details>\n<summary>Solution</summary>\n\n1. `products_loaded` has 4 columns instead of 3. The extra column is called `Unnamed: 0` and contains the numbers 0, 1, 2. It comes from the row index — when you save a DataFrame without specifying `index=False`, pandas writes the index as the first column in the file. When you reload the file, pandas reads that column as ordinary data because it has no way of knowing it was the index.\n\n::: {#28985849 .cell execution_count=4}\n``` {.python .cell-code}\nimport pandas as pd\n\nproducts = pd.DataFrame({\n    \"product\":  [\"coffee\", \"tea\", \"juice\"],\n    \"price\":    [29.90, 35.00, 12.50],\n    \"quantity\": [3, 5, 0]\n})\n\nproducts.to_csv(\"data/products.csv\")\n\nproducts_loaded = pd.read_csv(\"data/products.csv\")\nprint(products_loaded)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Unnamed: 0 product  price  quantity\n0           0  coffee   29.9         3\n1           1     tea   35.0         5\n2           2   juice   12.5         0\n```\n:::\n:::\n\n\n2. Add `index=False` to the `to_csv()` call:\n\n::: {#a0652fe2 .cell execution_count=5}\n``` {.python .cell-code}\nimport pandas as pd\n\nproducts = pd.DataFrame({\n    \"product\":  [\"coffee\", \"tea\", \"juice\"],\n    \"price\":    [29.90, 35.00, 12.50],\n    \"quantity\": [3, 5, 0]\n})\n\nproducts.to_csv(\"data/products.csv\", index=False)\n\nproducts_loaded = pd.read_csv(\"data/products.csv\")\nprint(products_loaded)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  product  price  quantity\n0  coffee   29.9         3\n1     tea   35.0         5\n2   juice   12.5         0\n```\n:::\n:::\n\n\nThis is one of the most common mistakes when saving DataFrames. Always use `index=False` unless you have specifically set a meaningful index (such as a date or a country name) that you want to preserve.\n\n</details>\n\n---\n\n### Exercise 3.1.5\n\nA colleague sends you a CSV file exported from Excel. When you try to load it, something looks wrong:\n\n```python\nimport pandas as pd\n\ndf = pd.read_csv(\"data/titanic_semicolon.csv\")\nprint(df.shape)\nprint(df.head())\n```\n\nInstead of 891 rows and 15 columns, the output shows 891 rows and **1 column**, and the single column contains values like `\"survived;pclass;sex;age;fare;...\"`.\n\n1. What has gone wrong?\n2. Fix the `read_csv()` call so the data loads correctly with all 15 columns.\n\nNote: the file `titanic_semicolon.csv` was created by the video code. If you do not have it yet, run this first:\n\n```python\ntitanic = pd.read_csv(\"data/titanic.csv\")\ntitanic.to_csv(\"data/titanic_semicolon.csv\", index=False, sep=\";\")\n```\n\n<details>\n<summary>Solution</summary>\n\n1. The file uses semicolons as the separator between columns instead of commas. By default, `read_csv()` expects commas. When it finds none, it treats each entire row as a single value and returns a DataFrame with one column containing all the fields joined together.\n\n2. Add `sep=\";\"` to tell pandas to split on semicolons instead:\n\n::: {#b2fb4ac4 .cell execution_count=6}\n``` {.python .cell-code}\nimport pandas as pd\n\ndf = pd.read_csv(\"data/titanic_semicolon.csv\", sep=\";\")\nprint(df.shape)\nprint(df.head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(891, 15)\n   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \\\n0         0       3    male  22.0      1      0   7.2500        S  Third   \n1         1       1  female  38.0      1      0  71.2833        C  First   \n2         1       3  female  26.0      0      0   7.9250        S  Third   \n3         1       1  female  35.0      1      0  53.1000        S  First   \n4         0       3    male  35.0      0      0   8.0500        S  Third   \n\n     who  adult_male deck  embark_town alive  alone  \n0    man        True  NaN  Southampton    no  False  \n1  woman       False    C    Cherbourg   yes  False  \n2  woman       False  NaN  Southampton   yes   True  \n3  woman       False    C  Southampton   yes  False  \n4    man        True  NaN  Southampton    no   True  \n```\n:::\n:::\n\n\nSemicolon-separated files are common in Europe, where the comma is used as the decimal separator in numbers. If you ever load a CSV and get a single column with all the data crammed together, a mismatched separator is almost always the cause. Open the raw file in a text editor to see which separator it actually uses.\n\n</details>\n\n",
    "supporting": [
      "03-01-importing-data_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}