{
  "hash": "50cbb20073f2472e193e4074d70155cb",
  "result": {
    "engine": "jupyter",
    "markdown": "# Filtering rows\n\nWe introduce boolean masks — Series of `True` and `False` values — to filter\nrows in a DataFrame based on a condition, and show how to combine multiple conditions to create more refined filters.\n\n{{< video https://vimeo.com/1195887665/dce7c220ea?fl=ml&fe=ec >}}\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# ── Boolean masks ────────────────────────────────────────────\n\n# First class passengers only\nmask = titanic[\"pclass\"] == 1\nmask.head()\n\n# Apply mask to DataFrame\nfirst_class = titanic[mask]\nfirst_class.head()\nfirst_class.shape\n\n# ── Multiple conditions ──────────────────────────────────────\n\n# First class female passengers\nfirst_class_women = titanic[\n    (titanic[\"pclass\"] == 1) &\n    (titanic[\"sex\"] == \"female\")\n]\nfirst_class_women.shape\n\n# Passengers who were either in first class OR survived\ncomfortable = titanic[\n    (titanic[\"pclass\"] == 1) |\n    (titanic[\"survived\"] == 1)\n]\ncomfortable.shape\n\n# ── Filtering with .isin() ──────────────────────────────────\n\n# Passengers in first or second class\nfirst_second = titanic[titanic[\"pclass\"].isin([1, 2])]\nfirst_second[\"pclass\"].value_counts()\n\n# ── Filtering with .query() ─────────────────────────────────\n\nsurvivors_first = titanic.query(\"survived == 1 and pclass == 1\")\nsurvivors_first.shape\n\n# ── Negating a filter with ~ ────────────────────────────────\n\n# Everyone except third class\nnot_third = titanic[~(titanic[\"pclass\"] == 3)]\nnot_third[\"pclass\"].value_counts()\n\n```\n\n## Exercises\n\n### Exercise 3.3.1\n\nA boolean mask is a Series of `True` and `False` values — one per row — that you can inspect before applying it. Run the code below and look at the output of each step.\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\nmask = titanic[\"age\"] < 18\nprint(mask.head(10))\nprint(mask.sum())\n```\n\n1. What does each row in the mask represent?\n2. What does `mask.sum()` tell you, and why does summing a boolean Series give a meaningful result?\n3. Apply the mask to the DataFrame, assign the result to `children`, and print its shape. Then calculate the survival rate among children as a share between 0 and 1.\n\n<details>\n<summary>Solution</summary>\n\n::: {#6b19c6ec .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\nmask = titanic[\"age\"] < 18\nprint(mask.head(10))\nprint(mask.sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0    False\n1    False\n2    False\n3    False\n4    False\n5    False\n6    False\n7     True\n8    False\n9     True\nName: age, dtype: bool\n113\n```\n:::\n:::\n\n\n::: {#4609a311 .cell execution_count=2}\n``` {.python .cell-code}\nchildren = titanic[mask]\nprint(children.shape)\nprint(children[\"survived\"].mean())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(113, 15)\n0.5398230088495575\n```\n:::\n:::\n\n\n1. Each row in the mask corresponds to one passenger. The value is `True` if that passenger was under 18 and `False` otherwise.\n\n2. `mask.sum()` gives the total number of passengers under 18. Python treats `True` as 1 and `False` as 0, so summing a boolean Series counts the number of `True` values — the same trick as using `.sum()` on the `survived` column in the previous video.\n\n3. There are 113 passengers under 18 in the dataset. Their survival rate is approximately 0.54, meaning about 54% of children survived — noticeably higher than the overall survival rate of around 38%.\n\n</details>\n\n---\n\n### Exercise 3.3.2\n\nFilter the `healthexp` dataset to rows for a single country of your choice and answer the following questions about that country.\n\n```python\nimport pandas as pd\n\nhealthexp = pd.read_csv(\"data/healthexp.csv\")\nhealthexp.head()\n```\n\n1. How many years of data are available for your chosen country?\n2. What is the minimum and maximum health spending recorded for that country?\n3. What is the mean life expectancy for that country across all available years?\n\n<details>\n<summary>Solution</summary>\n\n::: {#dd4c6cdb .cell execution_count=3}\n``` {.python .cell-code}\nimport pandas as pd\n\nhealthexp = pd.read_csv(\"data/healthexp.csv\")\n\nfrance = healthexp[healthexp[\"Country\"] == \"France\"]\n\nprint(france.shape[0])\nprint(france[\"Spending_USD\"].min())\nprint(france[\"Spending_USD\"].max())\nprint(france[\"Life_Expectancy\"].mean())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n35\n192.143\n5468.418\n79.5657142857143\n```\n:::\n:::\n\n\nThe results will differ depending on the country you choose. For France: 35 years of data are available, spending ranges from approximately 192 to 5468 USD, and mean life expectancy across all years is about 79.6 years. Notice that filtering to a single country returns a regular DataFrame — you can apply exactly the same summary methods as on the full dataset.\n\n</details>\n\n---\n\n### Exercise 3.3.3\n\nThe code below is intended to filter the Titanic dataset to adult male passengers who paid a fare above 50, but it contains an error. \n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\nexpensive_men = titanic[\n    titanic[\"sex\"] == \"male\" &\n    titanic[\"age\"] >= 18 &\n    titanic[\"fare\"] > 50\n]\n```\n\n1. Run the code. What error do you get, and why does it occur?\n2. Fix the code so it runs correctly and print the shape of the result.\n3. Extend the filter to also include female passengers who paid a fare above 50, regardless of age. Use `|` to combine this with the existing condition.\n\n<details>\n<summary>Hint</summary>\n\nEvery individual condition must be wrapped in its own parentheses when combining\nwith `&` or `|`. Without them, Python applies `&` before the comparison operators,\nwhich produces a `TypeError`.\n\n</details>\n\n<details>\n<summary>Solution</summary>\n\n::: {#69a519d3 .cell execution_count=4}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# 2. Fixed version\nexpensive_men = titanic[\n    (titanic[\"sex\"] == \"male\") &\n    (titanic[\"age\"] >= 18) &\n    (titanic[\"fare\"] > 50)\n]\nprint(expensive_men.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(59, 15)\n```\n:::\n:::\n\n\n::: {#800362cf .cell execution_count=5}\n``` {.python .cell-code}\n# 3. Extended with | to include high-paying women\nhigh_fare = titanic[\n    ((titanic[\"sex\"] == \"male\") & (titanic[\"age\"] >= 18) & (titanic[\"fare\"] > 50)) |\n    ((titanic[\"sex\"] == \"female\") & (titanic[\"fare\"] > 50))\n]\nprint(high_fare.shape)\nprint(high_fare[\"sex\"].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(146, 15)\nsex\nfemale    87\nmale      59\nName: count, dtype: int64\n```\n:::\n:::\n\n\n1. The error is a `TypeError`. Without parentheses around each condition, Python evaluates `&` before the comparison operators. This means it tries to apply `&` directly to the string `\"male\"` and the Series `titanic[\"age\"]`, which is not a valid operation.\n\n2. After wrapping each condition in parentheses, the filter works correctly and returns 59 passengers.\n\n3. When combining `&` and `|` in the same expression, group each `&` block in its own outer parentheses before joining them with `|`. This makes the logic explicit and avoids ambiguity about the order of evaluation.\n\n</details>\n\n---\n\n### Exercise 3.3.4\n\nThe `flights` dataset records monthly passenger numbers for US airlines from 1949 to 1960. Use it to practice alternative filtering approaches.\n\n```python\nimport pandas as pd\n\nflights = pd.read_csv(\"data/flights.csv\")\nflights.head()\n```\n\n1. Filter the data to the three summer months (June, July and August) using `|` to combine three separate conditions. Assign the result to `summer` and print its shape.\n2. Rewrite the same filter using `.isin()`. How does this compare to the approach in question 1?\n3. Rewrite the filter once more using `.query()`.\n4. Which approach do you find most readable? Is there a case where `.isin()` would be clearly preferable over `.query()`?\n\n<details>\n<summary>Solution</summary>\n\n::: {#97e8a095 .cell execution_count=6}\n``` {.python .cell-code}\nimport pandas as pd\n\nflights = pd.read_csv(\"data/flights.csv\")\n\n# 1. Using | to combine three conditions\nsummer = flights[\n    (flights[\"month\"] == \"Jun\") |\n    (flights[\"month\"] == \"Jul\") |\n    (flights[\"month\"] == \"Aug\")\n]\nprint(summer.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(36, 3)\n```\n:::\n:::\n\n\n::: {#490b3d9a .cell execution_count=7}\n``` {.python .cell-code}\n# 2. Using .isin()\nsummer = flights[flights[\"month\"].isin([\"Jun\", \"Jul\", \"Aug\"])]\nprint(summer.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(36, 3)\n```\n:::\n:::\n\n\n::: {#add814fe .cell execution_count=8}\n``` {.python .cell-code}\n# 3. Using .query()\nsummer_q = flights.query(\"month in ['Jun', 'Jul', 'Aug']\")\nprint(summer_q.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(36, 3)\n```\n:::\n:::\n\n\nAll three approaches return the same 36 rows — 3 months × 12 years.\n\n**Task 2:** `.isin()` is considerably more concise than chaining conditions with `|`. The difference becomes even more pronounced if you needed to filter for five or six months — chaining that many `|` conditions would be tedious to write and hard to read.\n\n**Task 4:** `.query()` is often more readable for simple conditions because the expression reads like a plain English sentence. `.isin()` tends to be preferable when the list of values is long, stored in a variable, or constructed dynamically — for example `flights[flights[\"month\"].isin(summer_months)]` where `summer_months` is a list defined elsewhere in your script. Embedding a long list directly inside a `.query()` string becomes harder to read and maintain.\n\n</details>\n\n---\n\n### Exercise 3.3.5\n\nUse the `healthexp` dataset to practice negation with `~`.\n\n```python\nimport pandas as pd\n\nhealthexp = pd.read_csv(\"data/healthexp.csv\")\nprint(healthexp[\"Country\"].unique())\n```\n\n1. Use `~` combined with `.isin()` to exclude the following countries from the dataset: `\"USA\"`, `\"Germany\"`, and `\"France\"`. Assign the result to `reduced` and verify the exclusion worked by printing the unique countries that remain.\n2. Extend the filter to also require that life expectancy is above 75. Use `&` to combine this with the negation condition.\n3. How many rows does the final filtered dataset contain?\n\n<details>\n<summary>Solution</summary>\n\n::: {#7a475f72 .cell execution_count=9}\n``` {.python .cell-code}\nimport pandas as pd\n\nhealthexp = pd.read_csv(\"data/healthexp.csv\")\n\n# 1. Exclude three countries\nexclude = [\"USA\", \"Germany\", \"France\"]\nreduced = healthexp[~healthexp[\"Country\"].isin(exclude)]\nprint(reduced[\"Country\"].unique())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<StringArray>\n['Great Britain', 'Japan', 'Canada']\nLength: 3, dtype: str\n```\n:::\n:::\n\n\n::: {#cbb37b90 .cell execution_count=10}\n``` {.python .cell-code}\n# 2. Also require life expectancy above 75\nreduced_high_life = healthexp[\n    ~healthexp[\"Country\"].isin(exclude) &\n    (healthexp[\"Life_Expectancy\"] > 75)\n]\nprint(reduced_high_life.shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(120, 4)\n```\n:::\n:::\n\n\n1. After excluding the three countries, the remaining unique countries are Great\nBritain, Japan and Canada.\n\n2. Combining `~` with `.isin()` and a numeric condition with `&` works exactly like combining any two conditions — the tilde simply negates the `.isin()` result before the `&` is applied.\n\n3. The final filtered dataset contains 120 rows.\n\n</details>\n\n",
    "supporting": [
      "03-03-filtering_files"
    ],
    "filters": [],
    "includes": {}
  }
}