{
  "hash": "218053e1c800974902431f50a73fc8ce",
  "result": {
    "engine": "jupyter",
    "markdown": "# Running multiple models\n\nWe use for loops to automate common regression workflows such as estimating the same model separately across subgroups, and progressively adding variables to build up a set of model specifications.\n\n*Video will be embedded*\n\n```python\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport statsmodels.formula.api as smf\n\nplt.style.use(\"seaborn-v0_8-whitegrid\")\n\ngapminder = pd.read_csv(\"data/gapminder.csv\")\ngap_2007  = gapminder[gapminder[\"year\"] == 2007].copy()\ngap_2007[\"log_gdp\"] = np.log(gap_2007[\"gdpPercap\"])\ngap_2007[\"pop_millions\"] = gap_2007[\"pop\"] / 1_000_000\n\n# --- Example 1: Same model across subgroups ---\n# Estimate the relationship between log GDP and life expectancy\n# separately for each continent\ncontinents = gap_2007[\"continent\"].unique()\ncontinent_results = []\n\nfor continent in continents:\n    subset = gap_2007[gap_2007[\"continent\"] == continent]\n\n    # Skip continents with too few observations to fit the model\n    if len(subset) < 3:\n        continue\n\n    fit = smf.ols(\"lifeExp ~ log_gdp\", data=subset).fit()\n\n    continent_results.append({\n        \"continent\":  continent,\n        \"coefficient\": fit.params[\"log_gdp\"],\n        \"ci_low\":     fit.conf_int().loc[\"log_gdp\", 0],\n        \"ci_high\":    fit.conf_int().loc[\"log_gdp\", 1],\n    })\n\ncontinent_df = pd.DataFrame(continent_results)\ncontinent_df\n\n# --- Bar plot with confidence intervals ---\nfig, ax = plt.subplots()\n\nax.barh(continent_df[\"continent\"], continent_df[\"coefficient\"], color=\"steelblue\")\nax.errorbar(continent_df[\"coefficient\"], continent_df[\"continent\"],\n            xerr=[continent_df[\"coefficient\"] - continent_df[\"ci_low\"],\n                  continent_df[\"ci_high\"] - continent_df[\"coefficient\"]],\n            fmt=\"none\", color=\"black\", capsize=3)\n\nax.set_xlabel(\"Coefficient on log GDP per capita\")\nax.set_title(\"Effect of log GDP on life expectancy by continent\")\n\nplt.show()\nplt.close()\n\n# --- Example 2: Progressively adding variables ---\n# Build model formulas programmatically using f-strings and join()\ncontrols = [\"log_gdp\", \"pop_millions\", \"C(continent)\"]\n\nmodels = []\n\nfor i in range(1, len(controls) + 1):\n    # join() combines list elements into a single string separated by \" + \"\n    rhs = \" + \".join(controls[:i])\n    formula = f\"lifeExp ~ {rhs}\"\n    print(f\"Model {i}: {formula}\")\n\n    models.append(smf.ols(formula, data=gap_2007).fit())\n\n# The list \"models\" now holds three fitted model objects\nprint(models[0].summary())\n```\n\n## Exercises\n\n### Exercise 5.3.1\n\nEstimate the relationship between `mpg` and `horsepower` separately for each `origin` group, following the same loop pattern shown in the video.\n\n```python\nimport seaborn as sns\nimport pandas as pd\nimport statsmodels.formula.api as smf\n\nmpg = sns.load_dataset(\"mpg\").dropna(subset=[\"horsepower\"])\n```\n\n1. Get the unique values of `origin`. Loop over them, and for each one: filter `mpg` to that group, skip it if it has fewer than 3 rows, fit `mpg ~ horsepower`, and append a dictionary with the group name, the coefficient on `horsepower`, and its 95% confidence interval to a list.\n2. Convert the list to a DataFrame called `origin_df` and print it. Which origin has the steepest (most negative) horsepower penalty?\n3. Now fit a single pooled model on the full `mpg` data using `horsepower * C(origin)` — the fully interacted model from exercise 5.1.5. Reconstruct each origin's slope by adding the relevant interaction coefficient to the main `horsepower` coefficient (remember, the reference category has no interaction term to add). Compare these reconstructed slopes to the ones in `origin_df`.\n4. The two approaches should give you the same coefficients. Name one practical difference between running separate regressions per group and running a single pooled model with full interactions.\n\n<details>\n<summary>Solution</summary>\n\n::: {#46eb4fde .cell execution_count=1}\n``` {.python .cell-code}\nimport seaborn as sns\nimport pandas as pd\nimport statsmodels.formula.api as smf\n\nmpg = sns.load_dataset(\"mpg\").dropna(subset=[\"horsepower\"])\n\n# 1-2. Loop over origin groups\norigins = mpg[\"origin\"].unique()\norigin_results = []\n\nfor origin in origins:\n    subset = mpg[mpg[\"origin\"] == origin]\n    if len(subset) < 3:\n        continue\n    fit = smf.ols(\"mpg ~ horsepower\", data=subset).fit()\n\n    origin_results.append({\n        \"origin\": origin,\n        \"coefficient\": fit.params[\"horsepower\"],\n        \"ci_low\": fit.conf_int().loc[\"horsepower\", 0],\n        \"ci_high\": fit.conf_int().loc[\"horsepower\", 1],\n    })\n\norigin_df = pd.DataFrame(origin_results)\nprint(origin_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   origin  coefficient    ci_low   ci_high\n0     usa    -0.121320 -0.134775 -0.107865\n1   japan    -0.230043 -0.287400 -0.172686\n2  europe    -0.221835 -0.280688 -0.162982\n```\n:::\n:::\n\n\n::: {#1177892d .cell execution_count=2}\n``` {.python .cell-code}\n# 3. Compare to the fully interacted pooled model\nmodel_int = smf.ols(\"mpg ~ horsepower * C(origin)\", data=mpg).fit()\nprint(model_int.params)\n\nb_hp = model_int.params[\"horsepower\"]\nb_hp_japan = model_int.params[\"horsepower:C(origin)[T.japan]\"]\nb_hp_usa = model_int.params[\"horsepower:C(origin)[T.usa]\"]\n\nprint(\"Europe slope (interaction model):\", b_hp)\nprint(\"Japan slope (interaction model):\", b_hp + b_hp_japan)\nprint(\"USA slope (interaction model):\", b_hp + b_hp_usa)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIntercept                        45.473726\nC(origin)[T.japan]                3.342488\nC(origin)[T.usa]                -10.997230\nhorsepower                       -0.221835\nhorsepower:C(origin)[T.japan]    -0.008208\nhorsepower:C(origin)[T.usa]       0.100515\ndtype: float64\nEurope slope (interaction model): -0.22183522355296903\nJapan slope (interaction model): -0.2300429524548467\nUSA slope (interaction model): -0.12132003702067533\n```\n:::\n:::\n\n\n2. Japan has the steepest horsepower penalty (about -0.23), followed closely by Europe (about -0.22). American cars have a notably flatter slope (about -0.12).\n\n3. The reconstructed slopes from the interaction model match the separately estimated slopes in `origin_df` exactly, since `europe` is the reference category (no interaction term needed) and the `japan`/`usa` interaction terms represent exactly the difference in slope needed to recover each group's own coefficient.\n\n4. Both approaches produce identical coefficient estimates when every variable is fully interacted with the group. They differ, however, in how the residual variance is estimated: separate regressions estimate it independently within each group, using only that group's own observations, while the pooled model assumes one common residual variance across all groups, estimated using the full sample. This means the pooled model's standard errors (and therefore its confidence intervals) can differ from the separate regressions' — often tighter, since it borrows statistical strength from the full dataset, which matters especially for smaller groups. The pooled model also lets you test directly whether a slope differs significantly between groups via the interaction term's p-value, something separate regressions do not give you automatically.\n\n</details>\n\n---\n\n### Exercise 5.3.2\n\nVisualize the `origin_df` results from the previous exercise as a horizontal bar chart with error bars, as shown in the video.\n\n```python\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\n# origin_df from exercise 5.3.1\n```\n\n1. Create a Figure and Axes, and plot `origin_df[\"coefficient\"]` against `origin_df[\"origin\"]` using `ax.barh()`.\n2. Add error bars using `ax.errorbar()`, with `xerr=` set to the distance from each coefficient to its lower and upper confidence bound, `fmt=\"none\"`, and `capsize=3`.\n3. Add axis labels and a title.\n4. Based on the chart, do the confidence intervals for the three origins overlap with each other, or are they clearly separated?\n\n<details>\n<summary>Solution</summary>\n\n::: {#d0a5121c .cell execution_count=3}\n``` {.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\norigin_df = pd.DataFrame({\n    \"origin\": [\"usa\", \"japan\", \"europe\"],\n    \"coefficient\": [-0.121320, -0.230043, -0.221835],\n    \"ci_low\": [-0.134775, -0.287400, -0.280688],\n    \"ci_high\": [-0.107865, -0.172686, -0.162982]\n})\n\nfig, ax = plt.subplots(figsize=(8, 5))\n\nax.barh(origin_df[\"origin\"], origin_df[\"coefficient\"], color=\"steelblue\")\nax.errorbar(\n    origin_df[\"coefficient\"], origin_df[\"origin\"],\n    xerr=[origin_df[\"coefficient\"] - origin_df[\"ci_low\"],\n          origin_df[\"ci_high\"] - origin_df[\"coefficient\"]],\n    fmt=\"none\", color=\"black\", capsize=3\n)\n\nax.set_xlabel(\"Coefficient on horsepower\")\nax.set_title(\"Effect of horsepower on mpg by origin\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](05-03-running-models_files/figure-html/cell-4-output-1.png){width=758 height=470}\n:::\n:::\n\n\n4. The confidence interval for the USA is clearly separated from Japan and Europe's intervals, suggesting American cars genuinely have a flatter horsepower-mpg relationship. Japan and Europe's intervals overlap substantially with each other, suggesting their slopes are not clearly distinguishable from one another given the sample size within each group.\n\n</details>\n\n---\n\n### Exercise 5.3.3\n\nCombine the subgroup loop from 5.3.1 with the regression-line visualization from Topic 5.2: plot each origin's regression line on the same scatter plot.\n\n```python\nimport seaborn as sns\nimport pandas as pd\nimport numpy as np\nimport statsmodels.formula.api as smf\nimport matplotlib.pyplot as plt\n\nmpg = sns.load_dataset(\"mpg\").dropna(subset=[\"horsepower\"])\n```\n\n1. Create a Figure and Axes with `figsize=(9, 6)`.\n2. Loop over each `origin` group. For each one: filter the data, plot the raw points as a scatter with `alpha=0.3` (no separate label needed for the points), fit `mpg ~ horsepower`, generate 50 evenly spaced `horsepower` values spanning that group's own range using `np.linspace()`, predict, and plot the resulting line with `label=origin`.\n3. Add axis labels, a title, and call `ax.legend()`.\n4. Do the three lines look roughly parallel, or do they clearly diverge? Does this match what you found in exercise 5.3.1?\n\n<details>\n<summary>Solution</summary>\n\n::: {#a10b034e .cell execution_count=4}\n``` {.python .cell-code}\nimport seaborn as sns\nimport pandas as pd\nimport numpy as np\nimport statsmodels.formula.api as smf\nimport matplotlib.pyplot as plt\n\nmpg = sns.load_dataset(\"mpg\").dropna(subset=[\"horsepower\"])\n\nfig, ax = plt.subplots(figsize=(9, 6))\n\nfor origin in mpg[\"origin\"].unique():\n    subset = mpg[mpg[\"origin\"] == origin]\n    fit = smf.ols(\"mpg ~ horsepower\", data=subset).fit()\n\n    hp_vals = np.linspace(subset[\"horsepower\"].min(), subset[\"horsepower\"].max(), 50)\n    new_data = pd.DataFrame({\"horsepower\": hp_vals})\n    new_data[\"predicted\"] = fit.predict(new_data)\n\n    ax.scatter(subset[\"horsepower\"], subset[\"mpg\"], alpha=0.3)\n    ax.plot(new_data[\"horsepower\"], new_data[\"predicted\"], label=origin)\n\nax.set_xlabel(\"Horsepower\")\nax.set_ylabel(\"Miles per gallon\")\nax.set_title(\"Fuel efficiency vs horsepower by origin, with fitted lines\")\nax.legend()\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](05-03-running-models_files/figure-html/cell-5-output-1.png){width=854 height=566}\n:::\n:::\n\n\n4. The American line is visibly flatter than the Japanese and European lines, which slope down more steeply and sit close to parallel with each other — the same pattern already visible numerically in the coefficients from exercise\n5.3.1. Building the chart this way makes that difference immediately visible, rather than requiring you to compare three separate numbers by eye.\n\n</details>\n\n---\n\n### Exercise 5.3.4\n\nPractice the progressive-variable loop pattern from the video, this time using `mpg` and its own set of explanatory variables.\n\n```python\nimport seaborn as sns\nimport pandas as pd\nimport statsmodels.formula.api as smf\n\nmpg = sns.load_dataset(\"mpg\").dropna(subset=[\"horsepower\"])\nmpg[\"weight_tons\"] = mpg[\"weight\"] / 1000\n```\n\n1. Define a list `controls = [\"horsepower\", \"weight_tons\", \"C(origin)\"]`.\n2. Loop over `range(1, len(controls) + 1)`. On each iteration, use `\" + \".join()` to build the right-hand side of the formula from `controls[:i]`, construct the full formula string with an f-string, print it, fit the model, and append the fitted model to a list called `models`.\n3. Print the `.summary()` of the last model in the list — the one with all three variables.\n\n<details>\n<summary>Solution</summary>\n\n::: {#0685d497 .cell execution_count=5}\n``` {.python .cell-code}\nimport seaborn as sns\nimport pandas as pd\nimport statsmodels.formula.api as smf\n\nmpg = sns.load_dataset(\"mpg\").dropna(subset=[\"horsepower\"])\nmpg[\"weight_tons\"] = mpg[\"weight\"] / 1000\n\ncontrols = [\"horsepower\", \"weight_tons\", \"C(origin)\"]\nmodels = []\n\nfor i in range(1, len(controls) + 1):\n    rhs = \" + \".join(controls[:i])\n    formula = f\"mpg ~ {rhs}\"\n    print(f\"Model {i}: {formula}\")\n    models.append(smf.ols(formula, data=mpg).fit())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nModel 1: mpg ~ horsepower\nModel 2: mpg ~ horsepower + weight_tons\nModel 3: mpg ~ horsepower + weight_tons + C(origin)\n```\n:::\n:::\n\n\n::: {#33405d8b .cell execution_count=6}\n``` {.python .cell-code}\nprint(models[-1].summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:                    mpg   R-squared:                       0.719\nModel:                            OLS   Adj. R-squared:                  0.716\nMethod:                 Least Squares   F-statistic:                     247.9\nDate:                Wed, 08 Jul 2026   Prob (F-statistic):          2.44e-105\nTime:                        13:11:13   Log-Likelihood:                -1112.2\nNo. Observations:                 392   AIC:                             2234.\nDf Residuals:                     387   BIC:                             2254.\nDf Model:                           4                                         \nCovariance Type:            nonrobust                                         \n======================================================================================\n                         coef    std err          t      P>|t|      [0.025      0.975]\n--------------------------------------------------------------------------------------\nIntercept             43.7011      0.932     46.871      0.000      41.868      45.534\nC(origin)[T.japan]     1.7811      0.696      2.558      0.011       0.412       3.150\nC(origin)[T.usa]      -0.9611      0.640     -1.501      0.134      -2.220       0.298\nhorsepower            -0.0535      0.011     -4.875      0.000      -0.075      -0.032\nweight_tons           -4.8427      0.545     -8.878      0.000      -5.915      -3.770\n==============================================================================\nOmnibus:                       35.026   Durbin-Watson:                   0.914\nProb(Omnibus):                  0.000   Jarque-Bera (JB):               47.308\nSkew:                           0.658   Prob(JB):                     5.33e-11\nKurtosis:                       4.078   Cond. No.                         576.\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n:::\n:::\n\n\nThe loop builds three increasingly complex formulas — `mpg ~ horsepower`, `mpg ~ horsepower + weight_tons`, and\n`mpg ~ horsepower + weight_tons + C(origin)` — using exactly the same `.join()` and slicing pattern as the video, just applied to a different list of controls.\n\n</details>\n\n---\n\n### Exercise 5.3.5\n\nUse the `models` list from the previous exercise to see how model fit changes as variables are added.\n\n```python\n# models list from exercise 5.3.4\n```\n\n1. Loop over `models` with `enumerate()`, starting the count at 1, and print each model's number alongside its R-squared, rounded to 4 decimal places.\n2. By how much does R-squared increase when `weight_tons` is added to the model with just `horsepower`? By how much does it increase again when `C(origin)` is added on top of that?\n3. Based on these increases, which variable contributes more additional explanatory power: `weight_tons` or `C(origin)`?\n\n<details>\n<summary>Solution</summary>\n\n::: {#368562fa .cell execution_count=7}\n``` {.python .cell-code}\nfor i, model in enumerate(models, start=1):\n    print(f\"Model {i} R-squared: {model.rsquared:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nModel 1 R-squared: 0.6059\nModel 2 R-squared: 0.7064\nModel 3 R-squared: 0.7193\n```\n:::\n:::\n\n\n2. R-squared rises from about 0.6059 to about 0.7064 when `weight_tons` is added — an increase of roughly 0.10. Adding `C(origin)` on top brings R-squared to about 0.7193 — a much smaller further increase of roughly 0.013.\n\n3. `weight_tons` contributes far more additional explanatory power than `C(origin)`. This is a useful pattern to notice: the biggest jumps in R-squared often come from the first one or two genuinely important variables, while\nadditional variables — even meaningful ones — tend to add progressively less once the main drivers are already in the model.\n\n</details>\n\n",
    "supporting": [
      "05-03-running-models_files"
    ],
    "filters": [],
    "includes": {}
  }
}