{
  "hash": "eb101dfaf9eb2ac84fd222fe41c77f8b",
  "result": {
    "engine": "jupyter",
    "markdown": "# Sorting and copying\n\nWe cover how to sort a DataFrame by one or more columns, how to\nreset the row index after sorting or filtering, and an important\ndistinction between views and copies — and why it matters when modifying a DataFrame.\n\n{{< video https://vimeo.com/1195887669/1f9146b4a2?fl=ml&fe=ec >}}\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# ── Sorting with .sort_values() ──────────────────────────────\n\ntitanic.sort_values(\"fare\", ascending=False)\n\n# The original is unchanged\ntitanic.head(5)\n\n# Assign back to store the sorted version\ntitanic = titanic.sort_values(\"fare\", ascending=False)\ntitanic.head()\n\n# ── Sorting by multiple columns ──────────────────────────────\n\ntitanic = titanic.sort_values([\"pclass\", \"fare\"], ascending=True)\ntitanic[[\"pclass\", \"fare\", \"survived\"]].head(10)\n\n# ── Resetting the index after sorting ────────────────────────\n\ntitanic.reset_index()\n\ntitanic = titanic.reset_index(drop=True)\ntitanic.head()\n\n# ── The view vs copy distinction and copy() ──────────────────\n\n# Filter out first-class passengers — may be a view in older pandas versions\nfirst_class = titanic[titanic[\"pclass\"] == 1]\nfirst_class[\"fare_rounded\"] = first_class[\"fare\"].round(0)\n\n# Best practice: use .copy() to create an independent DataFrame\nfirst_class = titanic[titanic[\"pclass\"] == 1].copy()\nfirst_class[\"fare_rounded\"] = first_class[\"fare\"].round(0)\n\n```\n\n## Exercises\n\n### Exercise 3.5.1\n\nThe code below attempts to sort the Titanic dataset by fare.\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\ntitanic.sort_values(\"fare\", ascending=False)\nprint(titanic.head())\n```\n\n1. Run the code. Is the output of `titanic.head()` sorted by fare? Why or why not?\n2. Fix the code so that `titanic` is permanently sorted by fare in descending order.\n3. After sorting, print the index of the first five rows using `titanic.index`. What do you notice, and why might this cause problems later?\n\n<details>\n<summary>Solution</summary>\n\n::: {#6bc13ca9 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# 1. Original - not sorted\nprint(titanic.head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \\\n0         0       3    male  22.0      1      0   7.2500        S  Third   \n1         1       1  female  38.0      1      0  71.2833        C  First   \n2         1       3  female  26.0      0      0   7.9250        S  Third   \n3         1       1  female  35.0      1      0  53.1000        S  First   \n4         0       3    male  35.0      0      0   8.0500        S  Third   \n\n     who  adult_male deck  embark_town alive  alone  \n0    man        True  NaN  Southampton    no  False  \n1  woman       False    C    Cherbourg   yes  False  \n2  woman       False  NaN  Southampton   yes   True  \n3  woman       False    C  Southampton   yes  False  \n4    man        True  NaN  Southampton    no   True  \n```\n:::\n:::\n\n\n::: {#876830a9 .cell execution_count=2}\n``` {.python .cell-code}\n# 2. Fixed - assign back\ntitanic = titanic.sort_values(\"fare\", ascending=False)\nprint(titanic.head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     survived  pclass     sex   age  sibsp  parch      fare embarked  class  \\\n679         1       1    male  36.0      0      1  512.3292        C  First   \n258         1       1  female  35.0      0      0  512.3292        C  First   \n737         1       1    male  35.0      0      0  512.3292        C  First   \n88          1       1  female  23.0      3      2  263.0000        S  First   \n438         0       1    male  64.0      1      4  263.0000        S  First   \n\n       who  adult_male deck  embark_town alive  alone  \n679    man        True    B    Cherbourg   yes  False  \n258  woman       False  NaN    Cherbourg   yes   True  \n737    man        True    B    Cherbourg   yes   True  \n88   woman       False    C  Southampton   yes  False  \n438    man        True    C  Southampton    no  False  \n```\n:::\n:::\n\n\n::: {#0e015542 .cell execution_count=3}\n``` {.python .cell-code}\n# 3. Index after sorting\nprint(titanic.index[:5].tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[679, 258, 737, 88, 438]\n```\n:::\n:::\n\n\n1. No — `titanic.head()` is not sorted. `.sort_values()` returns a new sorted DataFrame but does not modify `titanic` in place. The result is discarded because it is never assigned to anything.\n\n2. Assigning the result back to `titanic` with `titanic = titanic.sort_values(...)` updates the variable. This assign-back pattern is standard in pandas — most methods work this way.\n\n3. The index is no longer sequential (e.g. `[258, 737, 341, ...]`). After sorting, the row labels reflect the original positions in the unsorted DataFrame. This can cause confusing behavior when using `.loc[]`, since label 0 no longer refers to the first row in the sorted data.\n\n</details>\n\n---\n\n### Exercise 3.5.2\n\nContinue with the sorted `titanic` DataFrame from Exercise 3.5.1. The index is currently out of order after sorting.\n\n1. Reset the index without using `drop=True` and print the first three rows. What extra column appears, and where did it come from?\n2. Reset the index again with `drop=True` and assign the result back to `titanic`. Verify that the index now runs sequentially from 0.\n3. pandas also allows you to set an existing column as the index using `.set_index()`. Try setting the `embark_town` column as the index and print the first five rows. Then reflect on the following: what would make a column a good choice for an index? Is `embark_town` a good index for the Titanic dataset? Can you think of a column in any of the datasets we have used that would make a better index?\n\n<details>\n<summary>Solution</summary>\n\n::: {#84de3249 .cell execution_count=4}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\ntitanic = titanic.sort_values(\"fare\", ascending=False)\n\n# 1. Reset without drop=True\nprint(titanic.reset_index().head(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   index  survived  pclass     sex   age  sibsp  parch      fare embarked  \\\n0    679         1       1    male  36.0      0      1  512.3292        C   \n1    258         1       1  female  35.0      0      0  512.3292        C   \n2    737         1       1    male  35.0      0      0  512.3292        C   \n\n   class    who  adult_male deck embark_town alive  alone  \n0  First    man        True    B   Cherbourg   yes  False  \n1  First  woman       False  NaN   Cherbourg   yes   True  \n2  First    man        True    B   Cherbourg   yes   True  \n```\n:::\n:::\n\n\n::: {#32c4a42c .cell execution_count=5}\n``` {.python .cell-code}\n# 2. Reset with drop=True and assign back\ntitanic = titanic.reset_index(drop=True)\nprint(titanic.index[:5].tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[0, 1, 2, 3, 4]\n```\n:::\n:::\n\n\n::: {#9117b88b .cell execution_count=6}\n``` {.python .cell-code}\n# 3. Set embarkation town as index\ntitanic_port = titanic.set_index(\"embark_town\")\nprint(titanic_port.head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             survived  pclass     sex   age  sibsp  parch      fare embarked  \\\nembark_town                                                                    \nCherbourg           1       1    male  36.0      0      1  512.3292        C   \nCherbourg           1       1  female  35.0      0      0  512.3292        C   \nCherbourg           1       1    male  35.0      0      0  512.3292        C   \nSouthampton         1       1  female  23.0      3      2  263.0000        S   \nSouthampton         0       1    male  64.0      1      4  263.0000        S   \n\n             class    who  adult_male deck alive  alone  \nembark_town                                              \nCherbourg    First    man        True    B   yes  False  \nCherbourg    First  woman       False  NaN   yes   True  \nCherbourg    First    man        True    B   yes   True  \nSouthampton  First  woman       False    C   yes  False  \nSouthampton  First    man        True    C    no  False  \n```\n:::\n:::\n\n\n1. An extra column called `index` appears as the first column. It contains the old index labels — the original row positions before sorting. pandas preserves the old index as a column in case you need it, but in most cases it is just clutter.\n\n2. After `reset_index(drop=True)`, the index runs `[0, 1, 2, 3, 4, ...]` as expected.\n\n3. A good index column should uniquely identify each row, be stable (unlikely to change), and be something you will frequently use to look up rows. `embark_town` is a poor choice for the Titanic dataset for two reasons: long strings are cumbersome to type when using `.loc[]`, and town of embarkation is not unique — there are many passengers who departed from the same town. In fact, none of the Titanic columns are ideal as an index. In general, integer row numbers are a perfectly reasonable default index for most datasets.\n\n</details>\n\n---\n\n### Exercise 3.5.3\n\nSort the `healthexp` dataset first by `Country` alphabetically and then by `Year` within each country, but with the most recent year first.\n\n```python\nimport pandas as pd\n\nhealthexp = pd.read_csv(\"data/healthexp.csv\")\n```\n\n1. Sort the data as described above and assign the result back to `healthexp`. Print the first 10 rows to verify the result looks correct.\n2. Now look up the `na_position=` parameter in the documentation for `pd.DataFrame.sort_values()`. What does it control?\n3. The Titanic dataset has missing values in the `age` column. Sort `titanic` by `age` in ascending order and use `na_position=` to place passengers with missing ages at the top of the result. Print the first five rows to confirm.\n\n<details>\n<summary>Hint</summary>\n\nYou can look up the documentation by running `help(pd.DataFrame.sort_values)` in the console or simply search online for \"pandas sort_values\". For question 1, recall that you can pass a list of column names to sort by multiple columns, and a matching list to `ascending=` to control the\ndirection of each column independently.\n\n</details>\n\n<details>\n<summary>Solution</summary>\n\n::: {#9a0b0d55 .cell execution_count=7}\n``` {.python .cell-code}\nimport pandas as pd\n\nhealthexp = pd.read_csv(\"data/healthexp.csv\")\n\n# 1. Sort by Country ascending, Year descending\nhealthexp = healthexp.sort_values(\n    [\"Country\", \"Year\"],\n    ascending=[True, False]\n)\nprint(healthexp.head(10))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Year Country  Spending_USD  Life_Expectancy\n268  2020  Canada      5828.324             81.7\n262  2019  Canada      5189.721             82.2\n256  2018  Canada      5308.356             82.0\n250  2017  Canada      5150.470             81.9\n244  2016  Canada      5044.275             82.0\n238  2015  Canada      4635.285             81.9\n232  2014  Canada      4536.810             81.8\n226  2013  Canada      4428.753             81.7\n220  2012  Canada      4336.249             81.6\n214  2011  Canada      4228.962             81.4\n```\n:::\n:::\n\n\n::: {#23452fb5 .cell execution_count=8}\n``` {.python .cell-code}\n# 3. Sort titanic by age with NaN at the top\ntitanic = pd.read_csv(\"data/titanic.csv\")\ntitanic_sorted = titanic.sort_values(\"age\", ascending=True, na_position=\"first\")\nprint(titanic_sorted[[\"survived\", \"pclass\", \"sex\", \"age\"]].head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    survived  pclass     sex  age\n5          0       3    male  NaN\n17         1       2    male  NaN\n19         1       3  female  NaN\n26         0       3    male  NaN\n28         1       3  female  NaN\n```\n:::\n:::\n\n\n1. Passing a list to `ascending=` lets you control each column independently — `True` for `Country` (A to Z) and `False` for `Year` (most recent first).\n\n2. `na_position=` controls where missing values end up after sorting. The default is `\"last\"`, which places `NaN` values at the bottom. Setting it to `\"first\"` moves them to the top. This is useful when you want to quickly identify rows with missing data.\n\n</details>\n\n---\n\n### Exercise 3.5.4\n\nThis exercise is about understanding what `.copy()` does and why it matters depending on which version of pandas you are running.\n\n**Step 1.** Check your pandas version by running:\n\n```python\nimport pandas as pd\nprint(pd.__version__)\n```\n\n**Step 2.** Read the following explanation, then answer the questions below.\n\nWhen you filter a DataFrame, pandas may return either a **view** — a window into the original DataFrame's memory — or a **copy** — an independent object. In pandas versions below 3.0, modifying a view could silently modify the original DataFrame, and pandas would raise a `SettingWithCopyWarning` to alert you. From pandas 3.0 onwards, filtering always returns a copy, so this warning no longer appears. However, calling `.copy()` explicitly is still good practice because it makes your intent clear to anyone reading your code.\n\n**Step 3.** Run the code below and answer the questions.\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# Without .copy()\nfirst_class = titanic[titanic[\"pclass\"] == 1]\nfirst_class[\"fare_rounded\"] = first_class[\"fare\"].round(0)\n\n# With .copy()\nfirst_class_copy = titanic[titanic[\"pclass\"] == 1].copy()\nfirst_class_copy[\"fare_rounded\"] = first_class_copy[\"fare\"].round(0)\n```\n\n1. Does your pandas version raise a `SettingWithCopyWarning` when running the first block? What does this tell you about your version?\n2. Check whether `titanic` has a `fare_rounded` column after running both blocks. What does this tell you about whether `first_class` and `first_class_copy` are independent of the original?\n3. Even if your version of pandas does not require `.copy()`, why may it still be a good habit to use it?\n\n<details>\n<summary>Solution</summary>\n\n::: {#d6951bbd .cell execution_count=9}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# Without .copy()\nfirst_class = titanic[titanic[\"pclass\"] == 1]\nfirst_class[\"fare_rounded\"] = first_class[\"fare\"].round(0)\n\n# With .copy()\nfirst_class_copy = titanic[titanic[\"pclass\"] == 1].copy()\nfirst_class_copy[\"fare_rounded\"] = first_class_copy[\"fare\"].round(0)\n\nprint(\"fare_rounded\" in titanic.columns)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFalse\n```\n:::\n:::\n\n\n1. If your pandas version is 3.0 or above, no warning appears. If you see a `SettingWithCopyWarning`, your version is below 3.0 and you should update pandas — run `pip install --upgrade pandas` in your terminal.\n\n2. `titanic` does not have a `fare_rounded` column in either case, meaning both `first_class` and `first_class_copy` are independent of the original on pandas 3.0+. On older versions, the first block without `.copy()` could have modified `titanic` directly.\n\n3. Even when not strictly required, `.copy()` can be good practice because it makes your intent explicit — anyone reading the code immediately knows this subset is meant to be independent. It also ensures your code behaves consistently if it is ever run on an older version of pandas.\n\n</details>\n\n---\n\n### Exercise 3.5.5\n\nThis exercise brings together sorting, resetting the index, filtering with `.copy()`, and modifying a subset — the full workflow from this video.\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n```\n\n1. Sort `titanic` by `pclass` ascending and `fare` descending. Assign the result back and reset the index with `drop=True`.\n2. Filter to passengers in first class. Use `.copy()` to create an independent subset called `first_class`.\n3. Add a column `fare_category` to `first_class` using `np.where()` with the\nfollowing rules:\n    - `\"standard\"` if fare is 150 or below\n    - `\"premium\"` if fare is above 150\n4. Verify that `titanic` does not have a `fare_category` column, confirming that your modifications to `first_class` did not affect the original.\n\n<details>\n<summary>Solution</summary>\n\n::: {#7ed0d64e .cell execution_count=10}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# 1. Sort and reset index\ntitanic = titanic.sort_values([\"pclass\", \"fare\"], ascending=[True, False])\ntitanic = titanic.reset_index(drop=True)\nprint(titanic.head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   survived  pclass     sex   age  sibsp  parch      fare embarked  class  \\\n0         1       1  female  35.0      0      0  512.3292        C  First   \n1         1       1    male  36.0      0      1  512.3292        C  First   \n2         1       1    male  35.0      0      0  512.3292        C  First   \n3         0       1    male  19.0      3      2  263.0000        S  First   \n4         1       1  female  23.0      3      2  263.0000        S  First   \n\n     who  adult_male deck  embark_town alive  alone  \n0  woman       False  NaN    Cherbourg   yes   True  \n1    man        True    B    Cherbourg   yes  False  \n2    man        True    B    Cherbourg   yes   True  \n3    man        True    C  Southampton    no  False  \n4  woman       False    C  Southampton   yes  False  \n```\n:::\n:::\n\n\n::: {#ef70bbfe .cell execution_count=11}\n``` {.python .cell-code}\n# 2. Filter with .copy()\nfirst_class = titanic[titanic[\"pclass\"] == 1].copy()\n\n# 3. Add fare_category\nfirst_class[\"fare_category\"] = np.where(first_class[\"fare\"] > 150, \"premium\", \"standard\")\nprint(first_class[[\"fare\", \"fare_category\"]].head(10))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       fare fare_category\n0  512.3292       premium\n1  512.3292       premium\n2  512.3292       premium\n3  263.0000       premium\n4  263.0000       premium\n5  263.0000       premium\n6  263.0000       premium\n7  262.3750       premium\n8  262.3750       premium\n9  247.5208       premium\n```\n:::\n:::\n\n\n::: {#c0555504 .cell execution_count=12}\n``` {.python .cell-code}\n# 4. Verify original is unchanged\nprint(\"fare_category\" in titanic.columns)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFalse\n```\n:::\n:::\n\n\nThis workflow — sort, reset index, filter with `.copy()`, modify — is one you will repeat constantly in data analysis. Each step serves a purpose: sorting makes the data easier to inspect, resetting the index avoids confusing label behavior with `.loc[]`, and `.copy()` ensures modifications to the subset never silently affect the original DataFrame.\n\n</details>\n\n",
    "supporting": [
      "03-05-sorting-copying_files"
    ],
    "filters": [],
    "includes": {}
  }
}