{
  "hash": "4b02d3850a18d483320ce1d2db976be2",
  "result": {
    "engine": "jupyter",
    "markdown": "# Selecting columns and rows\n\nWe cover the core tools for subsetting a DataFrame: selecting single and multiple\ncolumns, and selecting rows by label with `.loc[]` or by position with `.iloc[]`.\n\n{{< video https://vimeo.com/1195888058/b6ac8e241f?fl=ml&fe=ec >}}\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# ── Selecting a single column ────────────────────────────────\n\nfares = titanic[\"fare\"]\ntype(fares)\nfares.head()\n\nfares.mean()\nfares.max()\n\ntitanic[\"survived\"].sum()    # total number of survivors\n\ntitanic[\"pclass\"].nunique()\ntitanic[\"pclass\"].unique()\ntitanic[\"pclass\"].value_counts()\n\n# ── Selecting multiple columns ───────────────────────────────\n\nsubset = titanic[[\"survived\", \"pclass\", \"sex\", \"age\", \"fare\"]]\nsubset.head()\n\n# ── Selecting rows with .loc[] — label-based ─────────────────\n\n# Single row\ntitanic.loc[0]\n\n# A range of rows — .loc[] is inclusive on both ends\ntitanic.loc[0:4]\n\n# A range of rows and specific columns\ntitanic.loc[0:4, [\"survived\", \"pclass\", \"sex\", \"age\"]]\n\n# ── Selecting rows with .iloc[] — position-based ────────────\n\n# Rows at positions 0, 1, 2 (stop=3 excluded), first 4 columns\ntitanic.iloc[0:3, 0:4]\n\n# Two last rows using negative indexing\ntitanic.iloc[-2]\n\n```\n\n## Exercises\n\n### Exercise 3.2.1\n\nThere are two ways to select a single column from a DataFrame, and they return different types of object. Run the code below and compare the output of each line.\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\nresult_a = titanic[\"age\"]\nresult_b = titanic[[\"age\"]]\n\nprint(type(result_a))\nprint(type(result_b))\n```\n\n1. What type does each expression return?\n2. What is the practical difference between a Series and a single-column DataFrame?\n3. When selecting multiple columns, which of the two forms must you use, and why?\n\n<details>\n<summary>Solution</summary>\n\n::: {#12afe84f .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\nresult_a = titanic[\"age\"]\nresult_b = titanic[[\"age\"]]\n\nprint(type(result_a))\nprint(type(result_b))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.Series'>\n<class 'pandas.DataFrame'>\n```\n:::\n:::\n\n\n1. `titanic[\"age\"]` returns a **Series** — a single column with its index on the left. `titanic[[\"age\"]]` returns a **DataFrame** — a table with one column.\n\n2. A Series is a one-dimensional object. A DataFrame is two-dimensional — it has both rows and named columns. Most summary methods (`.mean()`, `.sum()`) work on both, but some operations — such as saving to CSV or merging — expect a DataFrame.\n\n3. When selecting multiple columns you must pass a list of column names inside the square brackets, for example `titanic[[\"age\", \"fare\", \"pclass\"]]`. The outer brackets are the selection operator; the inner brackets create the Python list. This always returns a DataFrame regardless of how many columns you select.\n\n</details>\n\n---\n\n### Exercise 3.2.2\n\nUse the Titanic dataset to answer the following questions. Each question requires one of the column methods covered in the video: `.sum()`, `.value_counts()`, `.unique()`, or `.nunique()`.\n\n1. What share of passengers survived? \n2. How many unique ports of embarkation are in the dataset, and what are they?\n3. How many male and female passengers were there?\n4. Select only the `survived`, `pclass`, `sex`, and `fare` columns and display\nthe first five rows.\n\n<details>\n<summary>Solution</summary>\n\n::: {#bcb616e2 .cell execution_count=2}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# 1. Share of survivors (two alternatives)\nprint(titanic[\"survived\"].sum() / len(titanic))\nprint(titanic[\"survived\"].mean())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0.3838383838383838\n0.3838383838383838\n```\n:::\n:::\n\n\n::: {#5fb9b8a2 .cell execution_count=3}\n``` {.python .cell-code}\n# 2. Unique ports of embarkation\nprint(titanic[\"embarked\"].nunique())\nprint(titanic[\"embarked\"].unique())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n3\n<StringArray>\n['S', 'C', 'Q', nan]\nLength: 4, dtype: str\n```\n:::\n:::\n\n\n::: {#08bb287c .cell execution_count=4}\n``` {.python .cell-code}\n# 3. Male and female passengers \nprint(titanic[\"sex\"].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsex\nmale      577\nfemale    314\nName: count, dtype: int64\n```\n:::\n:::\n\n\n::: {#ead14e31 .cell execution_count=5}\n``` {.python .cell-code}\n# 4. Subset of columns\nsubset = titanic[[\"survived\", \"pclass\", \"sex\", \"fare\"]]\nprint(subset.head())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   survived  pclass     sex     fare\n0         0       3    male   7.2500\n1         1       1  female  71.2833\n2         1       3  female   7.9250\n3         1       1  female  53.1000\n4         0       3    male   8.0500\n```\n:::\n:::\n\n\n1. Approximately 38% of the passengers survived. Because `survived` is a binary variable coded as 0 and 1, `.sum()` adds up all the 1s, which equals the total number of survivors. You can then either divide this by the total number of passengers, or simply take the average value of the `survived` column.\n\n2. There are 3 unique ports (plus some missing values): `S` (Southampton),\n`C` (Cherbourg), and `Q` (Queenstown).\n\n3. `.value_counts()` shows that there are 577 male passengers and 314 passengers passengers in our data.\n\n</details>\n\n---\n\n### Exercise 3.2.3\n\n`.loc[]` and `.iloc[]` look similar but follow different slicing rules, and mixing them up is one of the most common sources of off-by-one errors in pandas.\n\nRun both selections below and compare the results.\n\n```python\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\nselection_a = titanic.loc[0:4]\nselection_b = titanic.iloc[0:4]\n```\n\n1. How many rows does each selection return? Why do they differ?\n2. Use `.iloc[]` to select the last 3 rows of the dataset without hardcoding the\ntotal number of rows.\n\n<details>\n<summary>Solution</summary>\n\n::: {#33993646 .cell execution_count=6}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\nselection_a = titanic.loc[0:4]\nselection_b = titanic.iloc[0:4]\n\nprint(len(selection_a))\nprint(len(selection_b))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n5\n4\n```\n:::\n:::\n\n\n::: {#b0829bcd .cell execution_count=7}\n``` {.python .cell-code}\n# Last 3 rows using negative indexing\nprint(titanic.iloc[-3:])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     survived  pclass     sex   age  sibsp  parch   fare embarked  class  \\\n888         0       3  female   NaN      1      2  23.45        S  Third   \n889         1       1    male  26.0      0      0  30.00        C  First   \n890         0       3    male  32.0      0      0   7.75        Q  Third   \n\n       who  adult_male deck  embark_town alive  alone  \n888  woman       False  NaN  Southampton    no  False  \n889    man        True    C    Cherbourg   yes   True  \n890    man        True  NaN   Queenstown    no   True  \n```\n:::\n:::\n\n\n1. `titanic.loc[0:4]` returns **5 rows** (rows 0, 1, 2, 3, and 4). `.loc[]` is **inclusive on both ends**, so the stop label 4 is included. `titanic.iloc[0:4]` returns **4 rows** (positions 0, 1, 2, 3). `.iloc[]` follows standard Python slicing rules where the stop is excluded. When the index is the default integer index, the label and the position are the same number — which makes the difference easy to miss. Always double-check which one you are using.\n\n2. `titanic.iloc[-3:]` uses negative indexing to count from the end. Omitting the stop returns everything from position `-3` to the end of the DataFrame.\n\n</details>\n\n---\n\n### Exercise 3.2.4\n\nUse `.loc[]` to extract a focused subset of the Titanic data: rows 10 through 20 (inclusive), keeping only the columns `survived`, `pclass`, `sex`, `age`, and `fare`. Assign the result to a variable called `sample`.\n\nThen answer the following questions using `sample`:\n\n1. What is the mean age of passengers in this sample?\n2. How many of the passengers in this sample survived?\n\n<details>\n<summary>Solution</summary>\n\n::: {#938c719c .cell execution_count=8}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\nsample = titanic.loc[10:20, [\"survived\", \"pclass\", \"sex\", \"age\", \"fare\"]]\nprint(sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    survived  pclass     sex   age     fare\n10         1       3  female   4.0  16.7000\n11         1       1  female  58.0  26.5500\n12         0       3    male  20.0   8.0500\n13         0       3    male  39.0  31.2750\n14         0       3  female  14.0   7.8542\n15         1       2  female  55.0  16.0000\n16         0       3    male   2.0  29.1250\n17         1       2    male   NaN  13.0000\n18         0       3  female  31.0  18.0000\n19         1       3  female   NaN   7.2250\n20         0       2    male  35.0  26.0000\n```\n:::\n:::\n\n\n::: {#72f975c0 .cell execution_count=9}\n``` {.python .cell-code}\nprint(sample[\"age\"].mean())\nprint(sample[\"survived\"].sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n28.666666666666668\n5\n```\n:::\n:::\n\n\n`.loc[]` accepts a row slice as the first argument and a list of column names as the second. Because `.loc[]` is inclusive on both ends, `10:20` returns 11 rows — labels 10 through 20. Note that `.mean()` on the `age` column automatically ignores missing values, so the result is based only on rows where age is recorded.\n\n</details>\n\n---\n\n### Exercise 3.2.5\n\nFor each of the four tasks below, decide whether `.loc[]` or `.iloc[]` is the more appropriate tool, then write the code.\n\n1. Select the row with index label `5`.\n2. Select the first row of the dataset.\n3. Select rows with index labels 100 through 105, keeping only `name`, `age`,\nand `fare`.\n4. Select the last row of the dataset without knowing how many rows it has.\n\n<details>\n<summary>Solution</summary>\n\n::: {#a5c2cba1 .cell execution_count=10}\n``` {.python .cell-code}\nimport pandas as pd\n\ntitanic = pd.read_csv(\"data/titanic.csv\")\n\n# 1. Row with index label 5 — use .loc[] because you know the label\nprint(titanic.loc[5])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsurvived                0\npclass                  3\nsex                  male\nage                   NaN\nsibsp                   0\nparch                   0\nfare               8.4583\nembarked                Q\nclass               Third\nwho                   man\nadult_male           True\ndeck                  NaN\nembark_town    Queenstown\nalive                  no\nalone                True\nName: 5, dtype: object\n```\n:::\n:::\n\n\n::: {#9de8f851 .cell execution_count=11}\n``` {.python .cell-code}\n# 2. First row — either works here, but .iloc[] is more explicit about position\nprint(titanic.iloc[0])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsurvived                 0\npclass                   3\nsex                   male\nage                   22.0\nsibsp                    1\nparch                    0\nfare                  7.25\nembarked                 S\nclass                Third\nwho                    man\nadult_male            True\ndeck                   NaN\nembark_town    Southampton\nalive                   no\nalone                False\nName: 0, dtype: object\n```\n:::\n:::\n\n\n::: {#a45dc22c .cell execution_count=12}\n``` {.python .cell-code}\n# 3. Labels 100–105 with specific columns — use .loc[]\nprint(titanic.loc[100:105, [\"sex\", \"age\", \"fare\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        sex   age     fare\n100  female  28.0   7.8958\n101    male   NaN   7.8958\n102    male  21.0  77.2875\n103    male  33.0   8.6542\n104    male  37.0   7.9250\n105    male  28.0   7.8958\n```\n:::\n:::\n\n\n::: {#85e303a5 .cell execution_count=13}\n``` {.python .cell-code}\n# 4. Last row without knowing the length — use .iloc[] with negative indexing\nprint(titanic.iloc[-1])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsurvived                0\npclass                  3\nsex                  male\nage                  32.0\nsibsp                   0\nparch                   0\nfare                 7.75\nembarked                Q\nclass               Third\nwho                   man\nadult_male           True\ndeck                  NaN\nembark_town    Queenstown\nalive                  no\nalone                True\nName: 890, dtype: object\n```\n:::\n:::\n\n\nTasks 1 and 3 are naturally label-based — you know the index values you want, so `.loc[]` is the right choice. Task 2 could use either, but `.iloc[0]` makes the intent clear: you want the first position. Task 4 requires `.iloc[]` because negative indexing is not supported by `.loc[]` — there is no label `-1` in a default integer index.\n\nAs a rule of thumb: use `.loc[]` when you know the label, and `.iloc[]` when you need a specific position or want to count from the end.\n\n</details>\n\n",
    "supporting": [
      "03-02-subsetting_files"
    ],
    "filters": [],
    "includes": {}
  }
}